import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { pretendard } from '@/lib/fonts/pretendard';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// TODO: 앱 로고 확정시 수정 필요
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${pretendard.variable} ${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="font-pretendard antialiased overflow-x-hidden">
        {/* 모바일 기기 safe area 대응 */}
        <div
          className="
            mx-auto w-full max-w-[428px] min-h-svh bg-white
            pt-[env(safe-area-inset-top)] pb-[env(safe-area-inset-bottom)]
          "
        >
          <div className="px-6">{children}</div>
        </div>
      </body>
    </html>
  );
}
